name: 'pr-test'
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install --ignore-scripts
      - run: |
          npm run build
      - run: |
          npm run package
      - uses: ./
